### ISSUE TITLE
Git submodules not being initialized?

### ISSUE THREAD

**Issue by Hoverbear** [nix-community/naersk#110]
Hi!

I'm trying to use this tool to build https://github.com/timberio/vector/commit/0836bcdc0c63e35061c003079edff06af6e3f198 which depends on https://github.com/bytecodealliance/lucet/commit/d741e2e30df19d1f8abd1a8660219ac494336b76 

You can see here, one of the subcrates of `lucet`, `lucet-wasi`, depends on `wasi-common` which is a git submodule in the root. 

![image](https://user-images.githubusercontent.com/130903/85203794-f1e6f280-b2c4-11ea-9324-b8bbf2207a3f.png)

https://github.com/bytecodealliance/lucet/blob/d741e2e30df19d1f8abd1a8660219ac494336b76/lucet-wasi/Cargo.toml#L25

![image](https://user-images.githubusercontent.com/130903/85203812-0dea9400-b2c5-11ea-96ab-c77955c0e143.png)

![image](https://user-images.githubusercontent.com/130903/85203827-22c72780-b2c5-11ea-887f-84070457a728.png)

This seems to not be handled. :(

![image](https://user-images.githubusercontent.com/130903/85203667-20180280-b2c4-11ea-8c9d-7f16ae9395ca.png).

You can reproduce this with:

```git
git clone git@github.com:timberio/vector.git
git checkout 0836bcdc0c63e35061c003079edff06af6e3f198
make neu-release-binary-x86_64-unknown-linux-gnu
```

I see https://github.com/NixOS/nix/pull/3166 but haven't managed to invoke it.

![image](https://user-images.githubusercontent.com/130903/85204639-b4856380-b2ca-11ea-9ab1-1a8dba1b3f38.png)

**Comment by nmattia** [comment]
> I see NixOS/nix#3166 but haven't managed to invoke it.

The PR was merged very recently, did you install the latest `nix` executable?

**Comment by Hoverbear** [comment]
It's sadly not on the latest `nixos-unstable` :(

```
vector on  nix-builds [$!?] is 📦 v0.10.0 via ⬢ v12.18.0 via 🦀 v1.44.0 via ❄️  impure took 2s 
❯ nix repl                                                      
Welcome to Nix version 2.3.6. Type :? for help.

nix-repl> builtins.fetchGit { url = ""; submodules = true; }
error: unsupported argument 'submodules' to 'fetchGit', at (string):1:31
```

This is the latest: https://github.com/NixOS/nix/releases/tag/2.3.6

**Comment by evanjs** [comment]
I have been using e.g. `nix run nixpkgs.nixUnstable --command nix-build -E "(with import <nixpkgs> {}; callPackage "./${1-default.nix}" {})" --show-trace` to get submodule support, but have been encountering #109, so I can't say whether it's working or not :P

**Comment by evanjs** [comment]
So this seems to happen for git dependencies in `Cargo.toml`, in my case.
Output of (`lib.traceVal e`) @ https://github.com/nmattia/naersk/blob/dcee40445cfe301ced2d1b11290d6a94ff3aadb9/build.nix#L158
`trace: { checkout = <CODE>; key = <CODE>; name = "spi_ccp"; url = "<private-git-url>"; }`

Dependency from Cargo.toml:
`spi_ccp = { git = "<private-git-url>", version = "1.0.0" }`

**Comment by nmattia** [comment]
Thanks @evanjs ! What's the content of `1-default.nix`? Did you have to tweak naersk to make it work?

**Comment by evanjs** [comment]
`${1-default.nix}` allows the command to fallback to `default.nix` if `$1` is not given via [substitution](https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html)

<details>
<summary>Contents of <span><code>default.nix</code></span></summary>

``` nix
{ stdenv
, callPackage
, sources ? import ../../../nix/sources.nix
# build inputs
, pkg-config
, udev

}:
let
  pname = "spi_ccp";
  version = "1.0.0";
  cargoLock = ./Cargo.lock;
  src = stdenv.mkDerivation rec {
    inherit pname version;
      src = builtins.fetchGit {
        url = "<private-git-url>";
        rev = "<rev>";
      };
      installPhase = ''
        mkdir -p $out $out/
        cp -R ./* $out/
        cp ${cargoLock} $out/Cargo.lock
      '';
    };
    naersk = callPackage sources.naersk {};
in
  naersk.buildPackage {
    name = pname;
    inherit src version;
    nativeBuildInputs = [
      pkg-config
    ];
    buildInputs = [
      udev
    ];
  }
```

</details>

The relevant bit being:
``` nix
src = builtins.fetchGit {
        url = "<private-git-url>";
        rev = "<rev>";
      };
```

Naersk did _not_ need to be modified to get this working, only Nix `2.4pre`
i.e. what is currently available via the `nixUnstable` attribute on `nixos-unstable` (I see `2.4pre20200721_ff314f1` on my desktop)

**Comment by Patryk27** [comment]
This should be fixed now that we have https://github.com/nix-community/naersk/pull/231 merged.

Please feel free to re-open this ticket if the issue still appears 🙂
