### ISSUE TITLE
Having to "override" `rustc` and `cargo` via an overlay feels hacky and undeclarative

### ISSUE THREAD

**Issue by NobbZ** [nix-community/naersk#122]
To use a different version of the rust toolchain, one has to provide an overlay that shadows `rustc` and `cargo` attributes with the versions of the rust toolchain one actually wants.

The approach taken by the regular `rustPlatform.buildRustPackage` to actually build a new `rustPlatform` which carries appropriate toollchain versions feels a lot more clean and in the spirit of dependency injection.

I'd appreciate a similar interface for `naersk`.

**Comment by Pauan** [comment]
(Note: any solution would have to work with custom targets, e.g. `wasm32-unknown-unknown`)

**Comment by nmattia** [comment]
Hi @NobbZ ! You should be able to pass in whichever [`cargo`](https://github.com/nmattia/naersk/blob/d645515b7159c75087b3d51f23a68047c2c09699/default.nix#L1) and [`rustc`](https://github.com/nmattia/naersk/blob/d645515b7159c75087b3d51f23a68047c2c09699/default.nix#L10). Have you tried that? Unless I misunderstood what you need here!

**Comment by NobbZ** [comment]
`README.md` says, that when I want non-standard rust versions, I have to "overlay" toplevel `rustc` and `cargo` attributes:

https://github.com/nmattia/naersk/blob/master/README.md#L89-L94

It would be nicer if there was an approach in which I had not to do that, but instead could pass in `rustc`/`cargo` as arguments or if there was a "platform" I could create, which would provide the tooling.

If I want to use regular `buildRustPackage` from `nixpkgs` with a non standard rust, it was just this:

```
let
  rustPlatform = makeRustPlatform {
    rustc = nightly.rust;
    cargo = nightly.rust;
  };
in rustPlatform.buildRustPackage { … }
```

Creating a "platform" feels more clean, and also would enable one to create multiple platforms to iterate over and produce many outputs to verify compatibility with another tool chain.

Also in the overlay approach, there is the potential that pure shell dependencies might be recompiled from scratch without any need, when the same `pkgs` is used for the `devShell` and `packages.*` (or their non-flake equivalents).

Though looking at the linked `default.nix`, a much simpler solution to use naersk with non-standard rust would actually be like this (which I currently can't test):

```
naerskLib = pkgs.callPackage naersk {
  rustc = nightly.rust;
  cargo = nightly.rust;
}
```

If it really works like this, then I really like to see it documented this way and would try to prepare a PR later today/tomorrow after I was able to test it.

**Comment by nmattia** [comment]
Hi @NobbZ ,

Yes, that's exactly how you should do it! Sorry if my message above wasn't clear. The lines you link to are only for using naersk with the mozilla overlay.

I agree we could have an example in the README, your PR would be very welcome!
