### ISSUE TITLE
buildInputs is ignored

### ISSUE THREAD

**Issue by P-E-Meunier** [nix-community/naersk#144]
If I do:

```
    buildInputs = [ pkgs.openssl pkgs.pkgconfig ];
```

The buildInputs seem to be completely ignored and the compilation fails (can't find openssl). However, the following works fine:

```
      override = x: (x // {
        buildInputs =
          x.buildInputs ++ (with pkgs; [ openssl pkgconfig ]);
      });
```

**Comment by malte-v** [comment]
I just ran into the same openssl/pkgconfig issue and I can't reproduce this problem with the latest `naersk`. `buildInputs` works fine for me.

**Comment by mhuesch** [comment]
as of the latest commit on `master` right now (c3e56b8a4ffb6d906cdfcfee034581f9a8ece571), I am able to use `buildInputs` successfully the "regular way".

excerpt:

```
          naersk'.buildPackage {
            src = ./.;
            copyLibs = true;
            buildInputs = with pkgs; [
              openssl
              pkgconfig
            ];
          };
```

**Comment by yuri-potatoq** [comment]
@P-E-Meunier  i had tha same issue and i'd solve it by put openssl deps into flake buildInputs.

**Comment by Patryk27** [comment]
Yeah, `buildInputs` should work now 🙂 Please feel free to re-open this ticket if you encounter any more problems.
