### ISSUE TITLE
Git dependencies with [patch.crates-io]

### ISSUE THREAD

**Issue by jD91mZM2** [nix-community/naersk#152]
Unfortunately, git dependencies in `[patch.crates-io]` aren't taken into account.

You can test it out [on this branch of rnix-lsp](https://github.com/nix-community/rnix-lsp/blob/57f340ae19cf0f76e452c2378b2c0c30d645f4ee/flake.nix#L16-L19). (There is a `default.nix` which uses flake-compat if you're not a user of nix flakes)

It's apparently not as simple as the following diff, otherwise I would have opened a PR. That seems to cause some issue where cargo thinks the lock file is out-of-date - very strange indeed.

``` diff
diff --git a/lib.nix b/lib.nix
index c395c95..57f8245 100644
--- a/lib.nix
+++ b/lib.nix
@@ -81,7 +81,8 @@ rec
       let
       tomlDependencies = cargotoml:
         lib.filter (x: ! isNull x) (
-          lib.mapAttrsToList
+          lib.flip lib.mapAttrsToList
+            ((cargotoml.dependencies or { }) // (cargotoml.patch.crates-io or {}))
             (k: v:
               if ! (lib.isAttrs v && builtins.hasAttr "git" v)
               then null
@@ -115,7 +116,8 @@ rec
                     ref = val.tag;
                   });
                 }
-            ) cargotoml.dependencies or { });
+            )
+        );
       in
         lib.mapAttrs (_: tomlDependencies) cargotomls;
 
```

**Comment by LEXUGE** [comment]
Same issue here

**Comment by yusdacra** [comment]
https://github.com/yusdacra/naersk/commit/5a0df99a3ce4d26a902ff3ab086a4417466d978a this commit fixes that I believe. Veloren also uses `[patch.crates-io]`, and with that commit it works fine.

**Comment by Patryk27** [comment]
This should be fixed now that we have https://github.com/nix-community/naersk/pull/231 merged.

Please feel free to re-open this ticket if the issue still appears 🙂
