### ISSUE TITLE
Doesn't build with Cargo 1.53 and above because it adds "version = 3" to Cargo.lock

### ISSUE THREAD

**Issue by phip1611** [nix-community/naersk#176]
With lockfiles generated by Cargo 1.53 and above, `naersk` fails with  `Not implemented: type int for key version`.

See Cargos changelog: https://github.com/rust-lang/cargo/blob/master/CHANGELOG.md

A lock file might look like this:

```toml
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "aead"
version = "0.3.2"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "7fc95d1bdb8e6666b2b217308eeeb09f2d6728d104be3e31916cc74d15420331"
dependencies = [
 "generic-array",
]

# ...
```

**Comment by tv42** [comment]
Not sure when things were changed, but I just built a `version = 3` crate with naersk e09c320446c5c2516d430803f7b19f5833781337.

**Comment by blitz** [comment]
@phip1611 I also cannot reproduce this. I'm happily building a Rust hello world with Rust nightly (with Cargo.lock file with `version = 3`). See my [playground](https://github.com/blitz/naersk-playground) repo. To run it yourself:

```
% nix-build https://github.com/blitz/naersk-playground/archive/master.tar.gz
...
% ./result/bin/test-crate 
Hello, world!
```

So I think the issue you are seeing is not related to Rust 1.53. Can you share a complete failing example?

**Comment by evanjs** [comment]
I am also getting this on a CI system... after successfully building on another desktop...

I copied most of the dependencies over to a [new repo](https://github.com/evanjs/naersk-playground) and was able to reproduce the issue when I used the [niv pins](https://github.com/evanjs/naersk-playground/blob/29aea3c569878790f79be8c59479aed1f310e686/nix/sources.json) that are currently used on the CI system and have pushed such to the [broken](https://github.com/evanjs/naersk-playground/tree/broken) branch.

**Comment by blitz** [comment]
@evanjs I can reproduce the issue with your branch after fixing the evaluation:

```
diff --git a/default.nix b/default.nix
index df33e2a19908..5e5374f190fd 100644
--- a/default.nix
+++ b/default.nix
@@ -1,7 +1,3 @@
-{ lib
-, ...
-}:
-
 let
   sources = import ./nix/sources.nix;
   pkgs = import sources.nixpkgs {};
```

After that I get the error with `nix-build`.

**Comment by blitz** [comment]
Commenting out the `version = 3` indeed fixes the issue and allows the derivation to be evaluated.

```
diff --git a/Cargo.lock b/Cargo.lock
index ee7d2e9b81b0..39b3ac561a6a 100755
--- a/Cargo.lock
+++ b/Cargo.lock
@@ -1,6 +1,6 @@
 # This file is automatically @generated by Cargo.
 # It is not intended for manual editing.
-version = 3
+#version = 3
 
 [[package]]
 name = "actix"

```

**Comment by Patryk27** [comment]
This should be working now (e.g. some of our tests have `version = 3` and they seem to be compiled alright); please feel free to re-open this ticket if the issue still appears 🙂
