### ISSUE TITLE
Move to nix-community?

### ISSUE THREAD

**Issue by Mic92** [nix-community/naersk#183]
https://old.reddit.com/r/NixOS/comments/ogy8vf/niv_naersk_napalm_moving_on/

You could simply transfer it to nix-community, we would assign you as a maintainer
but you could also add more people to the project as you wish.

**Comment by nmattia** [comment]
Done! https://github.com/nix-community/naersk

Note that I removed the `CACHIX_SIGNING_KEY` action secret. I'll keep the cache around for now but would be good to have someone update the push-to-cache config. Maybe https://www.reddit.com/user/jonringer117/, who showed interest in taking over maintainership? Don't know their GitHub handle unfortunately.

**Comment by Mic92** [comment]
We have a cachix key in nix-community afaik. I marked you as a maintainer. If you want to add more maintainers we can create a team in nix-community with access to the repo.

The person you are looking for is @jonringer

**Comment by nmattia** [comment]
@jonringer, should we create a team in nix-community with you and me as maintainers? I'm all for it.

**Comment by jonringer** [comment]
Sure, I just don't have admin access. cc @domenkozar

**Comment by Mic92** [comment]
I created a naersk team and invited you both. At least @nmattia should be able to add new people to the team.

**Comment by nmattia** [comment]
@Mic92 I actually cannot add @jonringer to the @nix-community/naersk team because he's not part of the nix-community org!

**Comment by Mic92** [comment]
invitation send.

**Comment by jonringer** [comment]
Sorry about that, all github email notifications get dumped into spam... I get around 50-500 github emails a day :/
