### ISSUE TITLE
Fails to pull some Git commits.

### ISSUE THREAD

**Issue by kevincox** [nix-community/naersk#195]
I'm having an issue where some Git commits fail to be pulled by git. They work fine when cargo clones them but fail when pulled by Nix via naersk.

For example:

```toml
[dependencies.lettre]
git = "https://github.com/gaetronik/lettre.git"
rev = "693a9ce0c896c6df27546c667a46b2c89743be0e"
```

But I am seeing this for many repos. Probably part of the problem is how git handled fetching exact refs rather than branches.

<pre><span style="background-color:#171421"><font color="#8B8A88">%</font></span><span style="background-color:#171421"><b> nix-build --show-trace -A feedmail</b></span>
fatal: not a tree object: 693a9ce0c896c6df27546c667a46b2c89743be0e
<font color="#C01C28"><b>error:</b></font> while evaluating the attribute &apos;builtDependencies&apos; of the derivation &apos;feedmail-0.0.0&apos; at <b>/nix/store/7q6z9p85m6d7q30wkmrdjd9rflvf7km3-nixos-21.11pre323695.9aeeb7574fb/nixos/pkgs/stdenv/generic/make-derivation.nix</b>:205:7:
while evaluating the attribute &apos;cargoconfig&apos; of the derivation &apos;feedmail-deps-0.0.0&apos; at <b>/nix/store/7q6z9p85m6d7q30wkmrdjd9rflvf7km3-nixos-21.11pre323695.9aeeb7574fb/nixos/pkgs/stdenv/generic/make-derivation.nix</b>:205:7:
while evaluating &apos;toTOML&apos; at <b>/nix/store/0h8fi90dhdyqjzl1li41dhhn173fa9ci-source/builtins/to-toml.nix</b>:119:12, called from <b>/nix/store/0h8fi90dhdyqjzl1li41dhhn173fa9ci-source/build.nix</b>:154:19:
while evaluating &apos;concatMapStringsSep&apos; at <b>/nix/store/7q6z9p85m6d7q30wkmrdjd9rflvf7km3-nixos-21.11pre323695.9aeeb7574fb/nixos/lib/strings.nix</b>:110:5, called from <b>/nix/store/0h8fi90dhdyqjzl1li41dhhn173fa9ci-source/builtins/to-toml.nix</b>:132:7:
while evaluating anonymous function at <b>/nix/store/0h8fi90dhdyqjzl1li41dhhn173fa9ci-source/builtins/to-toml.nix</b>:133:10, called from undefined position:
while evaluating anonymous function at <b>/nix/store/7q6z9p85m6d7q30wkmrdjd9rflvf7km3-nixos-21.11pre323695.9aeeb7574fb/nixos/lib/attrsets.nix</b>:259:10, called from undefined position:
while evaluating anonymous function at <b>/nix/store/0h8fi90dhdyqjzl1li41dhhn173fa9ci-source/builtins/to-toml.nix</b>:69:18, called from <b>/nix/store/7q6z9p85m6d7q30wkmrdjd9rflvf7km3-nixos-21.11pre323695.9aeeb7574fb/nixos/lib/attrsets.nix</b>:259:16:
while evaluating &apos;outputValInner&apos; at <b>/nix/store/0h8fi90dhdyqjzl1li41dhhn173fa9ci-source/builtins/to-toml.nix</b>:28:20, called from <b>/nix/store/0h8fi90dhdyqjzl1li41dhhn173fa9ci-source/builtins/to-toml.nix</b>:69:42:
while evaluating &apos;outputVal&apos; at <b>/nix/store/0h8fi90dhdyqjzl1li41dhhn173fa9ci-source/builtins/to-toml.nix</b>:41:15, called from <b>/nix/store/0h8fi90dhdyqjzl1li41dhhn173fa9ci-source/builtins/to-toml.nix</b>:39:9:
while evaluating the attribute &apos;paths&apos; of the derivation &apos;crates-io&apos; at <b>/nix/store/7q6z9p85m6d7q30wkmrdjd9rflvf7km3-nixos-21.11pre323695.9aeeb7574fb/nixos/pkgs/stdenv/generic/make-derivation.nix</b>:205:7:
while evaluating the attribute &apos;buildCommand&apos; of the derivation &apos;git-deps&apos; at <b>/nix/store/7q6z9p85m6d7q30wkmrdjd9rflvf7km3-nixos-21.11pre323695.9aeeb7574fb/nixos/pkgs/stdenv/generic/make-derivation.nix</b>:205:7:
program &apos;git&apos; failed with exit code 128
</pre>

**Comment by blitz** [comment]
I also see issues when using:
```toml
virtio-queue = { git = "https://github.com/cloud-hypervisor/cloud-hypervisor", tag = "v21.0" }
```

which results in the following while a normal cargo build succeeds:

```
fatal: couldn't find remote ref refs/heads/v21.0
error: program 'git' failed with exit code 128
(use '--show-trace' to show detailed location information)
```

**Comment by kevincox** [comment]
@blitz. That sounds like a different issue and I would recommend filing a new bug.

**Comment by blitz** [comment]
> @blitz. That sounds like a different issue and I would recommend filing a new bug.

Ok. I've opened #226.

**Comment by Patryk27** [comment]
This should be working now that you can pass `gitAllRefs = true;`; please feel free to re-open this ticket if the issue appears 🙂
