### ISSUE TITLE
CI appears to still be failing

### ISSUE THREAD

**Issue by efx** [nix-community/naersk#199]
We would like make CI pass again on the default development branch.
It is currently failing:
- https://github.com/nix-community/naersk/runs/4068990683?check_suite_focus=true#step:4:3612

We have tried a few things:
#197 
#198 

This issue captures further investigating why CI is failing and submitting a fix!

**Comment by ipetkov** [comment]
I *think* #203 should fix the failing CI builds (at least it passes all the tests locally, even when the previous commit would fail)

**Comment by Patryk27** [comment]
CI appears to be working correctly now, so let me go ahead and close this issue 🙂
