### ISSUE TITLE
Project needs more maintainers!

### ISSUE THREAD

**Issue by nmattia** [nix-community/naersk#206]
Hi there! 

This project needs some love. I do not have time to maintain it, and @jonringer is already [snowed under](https://github.com/nix-community/naersk/issues/183#issuecomment-902312399). If any kind soul feels like dedicating some love to this project, please speak up!

**Comment by blitz** [comment]
@nmattia Are you looking for a "full-time" maintainer or do you want to offload day-to-day things like code review and cleanups?

**Comment by nmattia** [comment]
@blitz mostly day-today things like code reviews and merging PRs. If there's any big feature that needs to be implemented then we'll see! but at least someone giving feedback to contributors would be great. :)

**Comment by jonringer** [comment]
Yea, I'm already the release manager for NixOS and already dedicated to many other things. I was a bit optimistic about being able to dedicate more time to this. :(

**Comment by blitz** [comment]
I'm happy to review code and also invest time in cleanups.

**Comment by Anderssorby** [comment]
I've been using this library a lot the last year and I would gladly help some. The docs and README need some updates and there are several features that I think would be nice.

**Comment by nmattia** [comment]
This is very much appreciated! I gave you both write access to the repo. Thanks for you help :)
