### ISSUE TITLE
local source (`./.`) removes submodules

### ISSUE THREAD

**Issue by wucke13** [nix-community/naersk#242]
I have a cargo workspace where one member is in a git submodule. The complete folder of this member is missing from the naersk build of that submodule (and thus the build fails, as one member can not be compiled). I'm using the cumbersome `'.?submodules=1'` notation to tell nix to include the submodule, which works for a minimal `stdenv.mkDerivation` test drv, but not for the naersk one. Does naersk somehow filter out submodules form `root`/`src`?

**Comment by Patryk27** [comment]
Could you try passing `gitSubmodules = true;` to `buildPackage`? (next to `name`, `src` etc.)

**Comment by Patryk27** [comment]
I'm 93.2137% certain that passing `gitSubmodules = true;` will solve the case, so lemme close this issue to avoid cluttering the view.

If something doesn't work, please feel free to re-open it 🙂
