### ISSUE TITLE
Building the wgpu triangle example

### ISSUE THREAD

**Issue by Anton-4** [nix-community/naersk#253]
I have set up a minimal reproduction of my issue [here](https://github.com/Anton-4/wgpu-triangle-naersk).

To reproduce the issue:
```
nix build
./result/bin/wgpu-triangle
```
This yields:
```
thread 'main' panicked at 'Failed to find an appropriate adapter', src/main.rs:20:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
The current hypothesis is that something is going wrong with how vulkan is linked.
I'll continue to try to solve this on Friday, but I thought I'd post it here in case anyone can help.

**Comment by Patryk27** [comment]
Hi,

Seems like it can be caused by a mismatch in the versions of libraries between the host machine and in the flake's nixpkgs, because - at least on my machine - changing `nixpkgs.url = "github:nixos/nixpkgs?ref=release-21.11";` to `nixpkgs.url = "github:nixos/nixpkgs";`, doing `nix flake update` and then `nix run` makes everything work 🤔

**Comment by Anton-4** [comment]
Interesting, thanks for helping out @Patryk27. Those changes did not work for me but I suspect that may be because you're on NixOS? I'm on Ubuntu 20.04.

**Comment by Anton-4** [comment]
Executing ` strace ./result/bin/wgpu-triangle ` confirmed my suspicions:
```
openat(AT_FDCWD, "/nix/store/0xxjx37fcy2nl3yz6igmv4mag2a7giq6-glibc-2.33-123/lib/libvulkan.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
```
As far as I can tell it's currently not possible to use nix for this case and end up with a binary that you can "just run" on other Linux systems with the same architecture. See also [this discussion on the nix discourse](https://discourse.nixos.org/t/do-gui-applications-not-work-on-non-nixos-using-nixpkgs-only/19070/3).

**Comment by Patryk27** [comment]
fwiw, [`nix bundle`](https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-bundle.html) might just do it.

**Comment by Anton-4** [comment]
Yeah, I did give that a try but I got the same error. Nix bundle's AppImage functionality could  work maybe :thinking:
