### ISSUE TITLE
Possible git tags fetcher regression

### ISSUE THREAD

**Issue by SkamDart** [nix-community/naersk#254]
https://github.com/nix-community/naersk/commit/2fc8ce9d3c025d59fee349c1f80be9785049d653 introduced a fix needed to fetch git tags during nix 2.4+.

A recent commit may have reintroduced https://github.com/nix-community/naersk/commit/8be5c0059de6f1ee7ae7d2a3ac4883f8c33ed963 reintroduced this bug?
https://github.com/nix-community/naersk/blob/8be5c0059de6f1ee7ae7d2a3ac4883f8c33ed963/lib.nix#L112-L114

**Comment by Patryk27** [comment]
Note that even for tag-based dependencies, `Cargo.lock` provides the revision hash - e.g.:
```toml
[[package]]
name = "rand"
version = "0.7.3"
source = "git+https://github.com/rust-random/rand?tag=0.7.3#074cb6a997f91db653f8a53c755ddc07495ab429"
dependencies = [
  # ...
]
```
... and, having merged to commit you've linked, we always pass that revision into `builtins.fetchGit`:
https://github.com/nix-community/naersk/blob/cddffb5aa211f50c4b8750adbec0bbbdfb26bb9f/lib.nix#L109

... so I think the logic is alright (plus we've got a test: https://github.com/nix-community/naersk/tree/cddffb5aa211f50c4b8750adbec0bbbdfb26bb9f/test/fast/git-dep-by-tag).

I've also re-checked and everything seems to be working correctly - do you maybe have a project that fails to be built or rather you're letting know just-in-case? 😄

**Comment by Patryk27** [comment]
To avoid cluttering the view, I'm going to close this issue - if you (or someone else!) finds the current behavior buggy, please feel free to re-open it 🙂
