### ISSUE TITLE
Cross compile to `aarch64-unknown-linux-{gnu,musl}` from `aarch64-apple-darwin`

### ISSUE THREAD

**Issue by DylanRJohnston** [nix-community/naersk#259]
Hey guys, I'm trying to compile a Rust project to an AWS Lambda. I've follow the cross compilation examples but I always up end failing to build `ring` as it appears to be trying to compile against `libSystem`.

I know it's possible at least theoretically because the [cargo-lambda](https://github.com/cargo-lambda/cargo-lambda) tool is able to do it just fine. From what I understand they end up using Zig for the linking phase. Is that something that naersk could do by override the right environment variables?

However from what I understand the compilation issue I'm hitting is occurring long before the linking phase and is because the nix environment is pointing the compiler towards the mac `libSystem` headers instead of the equivalent Linux header (glibc / musl?).

Anyone who could point me in the right direction would be greatly appreciated, but for now, in the interest of shipping I'm going to drop Nix for this project and just use `rustup` and `cargo-lambda`.

**Comment by DylanRJohnston** [comment]
Here's a sample of some of the errors while building `ring` using naersk.

```sh
 running "clang" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=aarch64-unknown-linux-musl" "-I" "include" "-Wall" "-Wextra" "-std=c1x" "-Wbad-function-cast" "-Wnested-externs" "-Wstrict-prototypes" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-g3" "-nostdlibinc" "-U_FORTIFY_SOURCE" "-DNDEBUG" "-DGFp_NOSTDLIBINC=1" "-c" "-o/private/tmp/nix-build-rust-workspace-deps-unknown.drv-2/dummy-src/target/aarch64-unknown-linux-musl/release/build/ring-cbc356963bebd1e7/out/aes_nohw.o" "crypto/fipsmodule/aes/aes_nohw.c"
  clang-11: warning: argument unused during compilation: '-mmacos-version-min=11.0' [-Wunused-command-line-argument]
  clang-11: warning: argument unused during compilation: '-nostdlibinc' [-Wunused-command-line-argument]
  clang-11: warning: argument unused during compilation: '-arch arm64' [-Wunused-command-line-argument]
  In file included from crypto/fipsmodule/aes/aes_nohw.c:15:
  In file included from include/GFp/aes.h:52:
  In file included from include/GFp/base.h:66:
  In file included from /nix/store/b9bh3z78rqff14bf0fd78xb07b5cnwdw-clang-wrapper-11.1.0/resource-root/include/stdint.h:52:
  In file included from /nix/store/amkqyy3v347mkdd9x1116nawinnc1r3j-libSystem-11.0.0/include/stdint.h:52:
  In file included from /nix/store/amkqyy3v347mkdd9x1116nawinnc1r3j-libSystem-11.0.0/include/sys/_types.h:32:
  /nix/store/amkqyy3v347mkdd9x1116nawinnc1r3j-libSystem-11.0.0/include/sys/cdefs.h:828:2: error: Unsupported architecture
  #error Unsupported architecture
   ^
```

```
 In file included from crypto/fipsmodule/aes/aes_nohw.c:15:
  In file included from include/GFp/aes.h:52:
  In file included from include/GFp/base.h:66:
  In file included from /nix/store/b9bh3z78rqff14bf0fd78xb07b5cnwdw-clang-wrapper-11.1.0/resource-root/include/stdint.h:52:
  In file included from /nix/store/amkqyy3v347mkdd9x1116nawinnc1r3j-libSystem-11.0.0/include/stdint.h:52:
  /nix/store/amkqyy3v347mkdd9x1116nawinnc1r3j-libSystem-11.0.0/include/sys/_types.h:55:9: error: unknown type name '__int64_t'
  typedef __int64_t       __darwin_blkcnt_t;      /* total blocks */
          ^
```

Like I said, I suspect the error is coming from the incorrect use of the `clang-wrapper` during compilation.

**Comment by Patryk27** [comment]
Hi, could you prepare some minimal source code I could `nix-build` / `nix build` locally to check it out? 🙂

**Comment by DylanRJohnston** [comment]
The full repository is here https://github.com/dylanrJohnston/splitwise, I'll try and shrink it down the smallest possible problem. I believe `reqwest` alone should be enough to cause trouble as it'll either try and link against OpenSSL, or with `default-features = false, features = ["json", "rustls-tls"]` it'll try and build `ring` which tries to build against `libSystem` headers.

**Comment by DylanRJohnston** [comment]
You can also find a failed GitHub Action run here where the host is Linux but the architecture is different from the target x86 vs aarch64, where the linker fails, I think this is where Zig would come in handy. https://github.com/DylanRJohnston/splitwise/runs/8065844608

**Comment by DylanRJohnston** [comment]
I've decided to just take the easy road out and change the lambda architecture to x86_64 and if I want to do local builds I can use rosetta + docker.
