### ISSUE TITLE
Private crate imported via ssh

### ISSUE THREAD

**Issue by gianarb** [nix-community/naersk#264]
Hello and thank you for your work. I think my use case is a little off.

My project is private and it imports a crate via github ssh:

```
[build-dependencies]
testprivate = { git = "ssh://git@github.com/test/testprivate.git", tag = "0.2.0"}
```

Most likely the problem is that the build environment can not connect to GitHub via ssh and it can't find the repo:

```
$ nix build
fetching Git repository 'ssh://git@github.com/test/testprivate.git'fatal: couldn't find remote ref refs/heads/0.2.0
error: program 'git' failed with exit code 128
```

I am not sure if I am reading the problem correctly, and I don't know how to do it properly.

**Comment by Patryk27** [comment]
Hi, could you try passing `gitAllRefs = true;` to your `buildPackage`'s invocation?

Fetching stuff from private repositories should work (as Nix already handles that for us), so it's something else that's off here.

**Comment by gianarb** [comment]
Hello @Patryk27 ! It works! I consued myself and I set to true `fetchGit.allRefs` instead of `gitAllRefs` to `naersk.buildPackage`!

Thank you for your support here!
