### ISSUE TITLE
How to cargo publish?

### ISSUE THREAD

**Issue by soywod** [nix-community/naersk#284]
So far I can compile my Rust project for linux and macos, and even cross compile for musl and windows using naersk with fenix. But how can I publish the crate? If I naively do a `nix shell -c cargo publish`, it rebuilds the project which I would like to avoid (it should take the deps from the nix store instead). Any idea?

**Comment by Patryk27** [comment]
You can always call `cargo publish --no-verify` which will avoid (re-)building the crate.

Note that publishing a crate doesn't publish any build-artifacts - Cargo always publishes only the source code, performing the build simply as a last-resort check to prevent people from shooting their feet - and so it wouldn't make much sense for Cargo to access `/nix/store` anyway, I think 👀

**Comment by soywod** [comment]
> You can always call `cargo publish --no-verify` which will avoid
> (re-)building the crate.

I will go for it then, thanks.

> also, note that Naersk is supposed to be only a "Rust to Nix"
> packaging bridge - it's not supposed to replace regular Cargo usage
> for development, building locally, testing locally etc.

Yes of course, but I wanted to avoid duplicate builds between Nix and
Cargo. The `--no-verify` option will do the trick!
