### ISSUE TITLE
two step builds fail if CMake is used in a `build.rs`

### ISSUE THREAD

**Issue by wucke13** [nix-community/naersk#285]
Some crates with C bindings use CMake to actually build the C library in question. This breaks with two step builds, the error could look like this:

```
 CMake Error: The current CMakeCache.txt directory /build/source/target/x86_64-unknown-linux-gnu/release/build/oqs-sys-c5d43ceffffee31f/out/build/CMakeCache.txt is different than the directory /build/dummy-src/target/x86_64-unknown-linux-gnu/release/build/oqs-sys-c5d43ceffffee31f/out/build where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
 ```
 
 Basically, CMake detects that the target folder was moved around, causing the build to fail. An easy hotfix would be:
 
 ```nix
 {
  #...
  overrideMain = x: x // {
    preBuild = x.preBuild + ''sed s_/dummy-src/_/source/_g --in-place "$(find -name CMakeCache.txt)"}'';
  };
}
```

Edit: Obviously its more elegant to use this as hotfix: `find -name CMakeCache.txt -exec sed s_/dummy-src/_/source/_g --in-place {} \;`

Hiding the evidence that trips of CMake.

**Comment by Patryk27** [comment]
Hi, I've tried to replicate it (even with the same dependency, `oqs`), and everything seems to be working fine 👀 

Could you prepare some failing case? (preferably a repository I could `git clone` and `nix-build` / `nix build` locally to see)

**Comment by wucke13** [comment]
@Patryk27 Yes, sure, above you find everything needed for a minimal example :smile:

**Comment by Patryk27** [comment]
Huh, that's interesting - it _does_ fail when I build it with your expression, but this one seems to work:

```nix
{ ... }:
naersk.buildPackage {
  src = ./app;

  nativeBuildInputs = with pkgs; [ clang cmake ];
  buildInputs = with pkgs; [ openssl ];

  LIBCLANG_PATH = "${pkgs.llvmPackages.libclang.lib}/lib";
}
```

Could you check this on your side as well?

**Comment by Patryk27** [comment]
Ah, right, that's probably because `CMakeCache.txt` dumps some envvars that are built differently when one uses `bindgenHook` vs writes `LIBCLANG_PATH` by hand; lemme see if we can safely bypass that on Naersk's side with your hook 🙂
