### ISSUE TITLE
Building crate that has a git submodule that is a crate that one depends on as a path dependency seems to fail?

### ISSUE THREAD

**Issue by molysgaard** [nix-community/naersk#287]
### Description 
I have rust crate, that lives in a git repo.
It has a dependency, that is a git submodule. And I am using
```toml
my-dependency = { path = ./path/to/submodule }
```
In my `Cargo.toml` to depend on it.

`nix build` fails.

I have created a test repository with a minimal reproducible example: https://github.com/molysgaard/naersk-issuereport

Maybe I am doing something wrong, if so, I would be very happy for guidance in how to do it right. If not, I am interested in support for this use case.

### Readme of minimal example repo below:

This repository shows an error I am getting when I am trying to use Naersk to compile a rust crate which has a git submodule inside it.

To reproduce:
``` bash
# clone the repo
git clone https://github.com/molysgaard/naersk-issuereport.git

# go into the new repository
cd naersk-issuereport

# fetch the repos submodule
git submodule update --init --recursive

# try to build using naersk
nix build
```

Observe the following error:
```
user@hostname:~/naersk-issuereport$ nix build
error: builder for '/nix/store/llvlnxiia6x2zasq7i462wyk5m3dgq9c-parent-crate-deps-0.1.0.drv' failed with exit code 101;
       last 10 log lines:
       >
       > Caused by:
       >   Unable to update /build/dummy-src/itoa
       >
       > Caused by:
       >   failed to read `/build/dummy-src/itoa/Cargo.toml`
       >
       > Caused by:
       >   No such file or directory (os error 2)
       > [naersk] cargo returned with exit code 101, exiting
       For full logs, run 'nix log /nix/store/llvlnxiia6x2zasq7i462wyk5m3dgq9c-parent-crate-deps-0.1.0.drv'.
error: 1 dependencies of derivation '/nix/store/lrfy8vpac86qdcy9i2ma57mkh02457h2-parent-crate-0.1.0.drv' failed to build
```

On inspecting the `dummy-src/` directory, there is no `itoa` directory, implying that the submodule has not been fetched for some reason.

**Comment by Patryk27** [comment]
Could you try passing gitSubmodules = true; to buildPackage? 👀

**Comment by molysgaard** [comment]
I think I am already doing it. Check the example repository?

**Comment by Patryk27** [comment]
Ah, right - I didn't see that on the phone 😅 

So, in this case you're actually hitting a limitation of Nix:
https://github.com/NixOS/nix/issues/6633
... where doing `src = ./.;` causes Nix to present the source directory to Naersk without the submodules.

This can be worked around by doing:
```nix
{ ... }:

defaultPackage = naersk-lib.buildPackage {
  src = self; # voilà
};
```

... committing all the changes (so that you have a clean Git tree, it's important) and then running:

```
nix build '.?submodules=1'
```

I think there's nothing Naersk could do on its side to overcome this issue, since we just read the `src` directory Nix prepares and there's no way to tell Nix to force-initialize-submodules from within Nix code.

Fortunately, there's a pull request to improve this:
https://github.com/NixOS/nix/pull/7862

**Comment by molysgaard** [comment]
I was able to get around this by removing the submodule and instead using cargo to fetch the dependency for me. Thanks for looking into this!

**Comment by xiej2520** [comment]
I had the same issue, doing `nix build '.?submodules=1'#` with `#` required, as mentioned by [this comment](https://github.com/NixOS/nix/issues/6633#issuecomment-2746304424) got Nix to fetch the submodule.
