### ISSUE TITLE
how do i build examples like cargo build --example example_name

### ISSUE THREAD

**Issue by GlennWSo** [nix-community/naersk#291]
Hi

As a lib developer i would like to know how i can use naersk to build examples.

Im have tried this:

>
        rust = pkgs.rust-bin.stable.latest.default;
        naersk-lib = naersk.lib."${system}".override {
          cargo = rust;
          rustc = rust;
        };
...
>
        defaultPackage = naersk-lib.buildPackage {
            pname = "three-d";
            src = ./.;
            cargoBuildOptions = defaultOptions: defaultOptions ++ ["--example=triangle"];
          };

my error:

>nix build
warning: Git tree '/home/gws/projects/three-d' is dirty
error: builder for '/nix/store/a7fy915fvpyhnvqvf1d7xxh2xakbckgw-three-d-deps-0.16.0.drv' failed with exit code 101;
       last 10 log lines:
       > [naersk] cargo_build_output_json (created): /build/tmp.8Y7thqTjkM
       > [naersk] crate_sources: /nix/store/p7id4ijz9csshr0a38i1l5b2pyinsdhj-dependencies
       > [naersk] RUSTFLAGS:
       > [naersk] CARGO_BUILD_RUSTFLAGS:
       > [naersk] CARGO_BUILD_RUSTFLAGS (updated): --remap-path-prefix /nix/store/p7id4ijz9csshr0a38i1l5b2pyinsdhj-dependencies=/sources
       > building
       > cargo build $cargo_release -j "$NIX_BUILD_CORES" --message-format=$cargo_message_format --example=triangle
       > error: no example target named `triangle`.
       >
       > [naersk] cargo returned with exit code 101, exiting
       For full logs, run 'nix log /nix/store/a7fy915fvpyhnvqvf1d7xxh2xakbckgw-three-d-deps-0.16.0.drv'.
error: 1 dependencies of derivation '/nix/store/mw1mi3xpp66xlsaw8vrsm1hpzjf5xv9h-three-d-0.16.0.drv' failed to build

Since "cargo build --example triangle" just works in my devshell i expected i could use naersk to build a --example

**Comment by GlennWSo** [comment]
i found a workaround. Build all the examples. And the match pname with the example u want to run when invoking `nix run`


```
defaultPackage = naersk-lib.buildPackage {
            pname = "triangle";
            src = ./.;
            buildInputs = deps;
            cargoBuildOptions = defaultOptions: defaultOptions ++ ["--examples"];
          };
```

**Comment by Patryk27** [comment]
Hi, adjusting `pname` is the correct approach here, although you could also try:

```
singleStep = true;
cargoBuildOptions = defaultOptions: defaultOptions ++ ["--example=triangle"];
```

**Comment by Patryk27** [comment]
Building all of the examples and adjusting `pname` is alright but if you need to build only a single example, you can do:

```
pname = "bar";
src = ./.;

overrideMain = x: {
  preConfigure = ''
    cargo_build_options="$cargo_build_options --example bar"
  '';
};
```

Arguably, it's a bit hacky and could use a better syntax, something in terms of:

```
pname = "bar";
src = ./.;

overrideMainConfig = x: {
  cargoBuildOptions = defaultOptions: defaultOptions ++ ["--example=triangle"];
};
```

(the issue with `cargoBuildOptions = ...;` is that Naersk actually compiles the code twice: first it creates a derivation that builds only the dependencies and then it creates a second derivation that compiles your own code - we do that so that rebuilding the code is faster if only your code changed because then the dependencies don't have to get rebuilt - but this `cargoBuildOptions` is applied also for the dependency-only derivation which doesn't contain the examples, causing the build to fail 👀 )

**Comment by GlennWSo** [comment]
@Patryk27 thanks, you gave me the exact info i was looking for :)

I dont think the syntax is that bad, but is not obvious. 
## suggestion

add this into examples, faq or tips and tricks & tricks
```nix
{
# ...
defaultPackage = {
  pname = "bar";
  src = ./.;

  overrideMain = x: {
    preConfigure = ''
      cargo_build_options="$cargo_build_options --example bar"
    '';
  };
};
}
```
