### ISSUE TITLE
Passing options to clippy

### ISSUE THREAD

**Issue by iensu** [nix-community/naersk#294]
Hi! I'd like to pass some configuration options to the `clippy` command but that doesn't seem to be possible currently:

```
cargo clippy $cargo_release -j "$NIX_BUILD_CORES" --message-format=$cargo_message_format -- -D warnings
```

Would it be possible to add a `$clippy_options` parameter after the `-D warnings` option so that you can run a command like:

```
cargo clippy $cargo_release -j "$NIX_BUILD_CORES" --message-format=$cargo_message_format -- -D warnings --warn clippy::pedantic 
```

Is this something you believe worth supporting?

**Comment by Patryk27** [comment]
Hi,

Yeah, it sounds like a nice feature!

I guess it would make sense to have something like:

```
  cargoCommand = let
      mode = attrs.mode;
    in
      if (mode == "build") then
        attrs.cargoBuild
      else if (mode == "check") then
        ''cargo $cargo_options check $cargo_build_options >> $cargo_build_output_json''
      else if (mode == "test") then
        ''cargo $cargo_options test $cargo_test_options >> $cargo_build_output_json''
      else if (mode == "clippy") then
        ''cargo $cargo_options clippy $cargo_build_options -- $cargo_clippy_options >> $cargo_build_output_json'' # <-- here
      else throw "Unknown mode ${mode}, allowed modes: build, check, test, clippy";
```
... with `cargo_clippy_options` defaulting to `-D warnings`.

I should be able to implement that over the weekend, but if you'd like to try yourself, feel free to 🙂

**Comment by iensu** [comment]
Great! I can have a go at it tomorrow :)
