### ISSUE TITLE
Project's build.rs file not getting executed at all

### ISSUE THREAD

**Issue by alerque** [nix-community/naersk#301]
I've been using naersk for my [decasify](https://github.com/alerque/decasify) project, and up until some recent changes I made it was working fine. The change I introduced is setting a rustc-cfg value in `build.rs`. This allows me to toggle some dependencies on or off depending on what phase of the build I'm in so completions script generators and such have access to what they need at the right time.

After adding this change, the Nix Flake stopped working because the value was not getting set at all and hence the dependencies were not being loaded up properly.

I fiddled with it some and it seems like the `build.rs` file is not being used *at all*:

```rust
fn main() {
    panic!("Did I even run");
}
```

Using `cargo run` will panic of course, but using `nix run .` I don't get a panic and it fails later in the build with not being able to find crates in scope.

I see several other issues mentioning `build.rs` but all of them make it sound like it is being used normally. I'm not passing anything too fancy via `cargoBuildOptions`, just one feature flag.

Is this expected? And if so how can I make the Flake build use `build.rs`?

**Comment by Patryk27** [comment]
> Is this expected?

Kinda-sorta - when you build something through Naersk, it actually builds two derivations:

- first, it builds only your application's dependencies,
- and then it builds your application.

This allows Naersk to perform a sort of incremental compilation when you do `nix build` - i.e. as long as your `Cargo.lock` doesn't change, the dependencies don't have to be rebuild, making incremental `nix build`s pretty fast.

Usually this mechanism works great, but it falls short on cases like `build.rs`s affecting how dependencies are built :eyes:

I'm afraid there's no golden bullet here - I'd suggest disabling Naersk's incremental compilation by setting `singleStep = true;`, i.e.:

```patch
diff --git a/default.nix b/default.nix
index dcf3f85..cde1376 100644
--- a/default.nix
+++ b/default.nix
@@ -16,9 +16,7 @@ naersk.lib."${targetPlatform.system}".buildPackage rec {
     rustc
   ];
   cargoBuildOptions = final: final ++ [ "--features cli" ];
-  # Work around naersk not using build.rs, see https://github.com/nix-community/naersk/issues/301
-  RUSTFLAGS = "--cfg build";
-  CARGO_BUILD_INCREMENTAL = "false";
+  singleStep = true;
   copyLibs = true;
   name = cargoToml.package.name;
   version = cargoToml.package.version;
```

**Comment by alerque** [comment]
Thanks, that's pretty useful. I knew about the two step compilation, but I didn't realize either that it could be disabled or that build.rs was being ignored as a direct result. It might be worth documenting the potential side effects as it is not that uncommon for processing of `build.rs` to be *required* to build properly.
