### ISSUE TITLE
dummy-src build failed with "cp: missing file operand"

### ISSUE THREAD

**Issue by cole-h** [nix-community/naersk#305]
```
dummy-src> cp: missing file operand
dummy-src> Try 'cp --help' for more information.
note: keeping build directory '/tmp/nix-build-dummy-src.drv-4'
error: builder for '/nix/store/y62b65nl4bq3zwj6kqm5a7387d2b9843-dummy-src.drv' failed with exit code 1;
       last 2 log lines:
       > cp: missing file operand
       > Try 'cp --help' for more information.
       For full logs, run 'nix log /nix/store/y62b65nl4bq3zwj6kqm5a7387d2b9843-dummy-src.drv'.
```

This happened when I updated naersk from d9a33d69a9c421d64c8d925428864e93be895dcc to 275010712ce41dff66634f9910bc1f085239b370.

**Comment by Patryk27** [comment]
Whoopsie, would you mind trying on 9bbe32cccfff5a44b7b75fb818e7739d500a07a7?

**Comment by cole-h** [comment]
Same issue, I'm afraid.

You should be able to reproduce with `nix build github:cole-h/nixos-config/naersk-debug#debug.x86_64-linux`.

**Comment by Patryk27** [comment]
Okie, confirmed, it fails on my machine as well - I'll take a look tomorrow.

**Comment by cole-h** [comment]
Just chiming in that this is confirmed fixed now, thanks :)

(For posterity: I've deleted the `naersk-debug` branch on my repo, so the above `nix build` won't work)
