### ISSUE TITLE
The 'proper' way of doing a debug build?

### ISSUE THREAD

**Issue by alxpettit** [nix-community/naersk#313]
What's the 'proper' approach to packaging something with both debug and release build targets?

My company's code is getting increasingly complicated, and ideally, we'd like to use naersk for reproducible iterated development builds during development phase, and not just during deployment phase. Is there any accepted convention for making this possible? (e.g., flake output names, recommended arguments for the `buildPackage` function to concisely toggle `--release` flag off, etc)

**Comment by Patryk27** [comment]
You can pass `release = false;` to `buildPackage` in order to skip the `--release` parameter, so maybe something like this will do:

```nix
{
  inputs = {
    flake-utils.url = "github:numtide/flake-utils";
    naersk.url = "github:nix-community/naersk";
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
  };

  outputs = { self, flake-utils, naersk, nixpkgs }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = (import nixpkgs) {
          inherit system;
        };

        naersk' = pkgs.callPackage naersk { };

        build = { release }: naersk'.buildPackage {
          inherit release;

          src = ./.;
        };

      in
      {
        defaultPackage = pkgs.linkFarm "app" [
          {
            name = "debug";
            path = build { release = false; };
          }

          {
            name = "release";
            path = build { release = true; };
          }
        ];
      }
    );
}
```

**Comment by alxpettit** [comment]
Oh, nifty! Had no idea that `buildPackage` arg existed. Thanks! :)

**Comment by alxpettit** [comment]
Oh, whoops. It was on the README.md the whole time. Aaagh :woman_facepalming:

**Comment by Patryk27** [comment]
No worries, there's lots of options there, so it's easy to miss 😄
