### ISSUE TITLE
Looking for a maintainer

### ISSUE THREAD

**Issue by Patryk27** [nix-community/naersk#314]
Hi,

Naersk is looking for a maintainer - if you know a bit of Nix and Rust, and would like to maintain Naersk, lemme know 🙂

**Comment by AxelSilverdew** [comment]
Hi, I know a wee bit of both, and I'm definitely interested.

I'd feel a bit more confident co-maintaining it with someone more experienced if possible though 😅

**Comment by Patryk27** [comment]
Hi, great! 🙂 

No worries, there's a code review system in place and you can feel free to ping me any time (both here and [on Matrix](https://matrix.to/#/#nix-community:nixos.org)) - I'll take a look tomorrow at the steps required to change the maintainer.
