### ISSUE TITLE
Dependencies with inherited workspace info fails with parse error

### ISSUE THREAD

**Issue by zaphar** [nix-community/naersk#318]
Example error output:

```
error: failed to get `candle-core` as a dependency of package `rust-ml v0.1.0 (/private/tmp/nix-build-rust-ml-de>

Caused by:
  failed to load source for dependency `candle-core`

Caused by:
  Unable to update https://github.com/huggingface/candle.git#f365a075

Caused by:
  failed to update replaced source https://github.com/huggingface/candle.git#f365a075

Caused by:
  failed to parse manifest at `/nix/store/w7ksk5wi648rilnd041nb9j1vxciy00d-git-dependencies/candle-core-0.3.0-f3>

Caused by:
  error inheriting `version` from workspace root manifest's `workspace.package.version`

Caused by:
  failed to find a workspace root
[naersk] cargo returned with exit code 101, exiting

```

This looks to be because the vendored crates lose their workspace root when copied. Currently Cargo has a similar problem when vendoring: https://github.com/rust-lang/cargo/issues/11192

However since naersk does it's own vendoring I'm not sure if you can rely on their eventual fix.

**Comment by commandodev** [comment]
cabal2nix also seems to be affected by this.

**Comment by Patryk27** [comment]
I think it's the same case as here: https://github.com/nix-community/naersk/issues/310#issuecomment-1738716629 👀

**Comment by zaphar** [comment]
Ahhh yes, Sorry I didn't realize there was already an issue for this. I missed that one in my search. Sorry about that.
