### ISSUE TITLE
Support cross compiling 

### ISSUE THREAD

**Issue by expipiplus1** [nix-community/naersk#79]
I guess this would involve using `rustc.nativeDrv` instead of `rustc` and changing some of the info passed to `cargo`. I'm no rust expert and wasn't able to get this working in a few minutes of trying.

**Comment by nmattia** [comment]
Hey @expipiplus1 , can you clarify what you mean by "cross compiling"? I've meant to add wasm and musl builds to naersk, just haven't found the time yet. I'll also need to write a guide on how I do it at $WORK. Do you mean more cross compilation targets?

**Comment by giodamelio** [comment]
Just running into this now. Wanting to do a `x86_64-unknown-linux-musl` build to be deployed to AWS Lambda. I will tinker with this a bit the next few days, but I am a total Nix beginner.

**Comment by nmattia** [comment]
Let me get started on this, I have the code lying around, just need to integrate it. First I want to extend the test suite to run on multiple nixpkgs versions, otherwise it's going to be hell to debug.

**Comment by nmattia** [comment]
https://github.com/nmattia/naersk/issues/88

**Comment by giodamelio** [comment]
Thanks so much! I gave it a shot, but it was a little much for my novice Nix skills.

If you need any help testing let me know, I can at least be a beta tester.

**Comment by nmattia** [comment]
Thanks! I've created a bunch of tickets: https://github.com/nmattia/naersk/issues?q=+is%3Aissue+label%3Amusl+

Last night I added a definition for `rustc` with a `wasm32` and a musl target (https://github.com/nmattia/naersk/issues/90). The next step is to actually provide a way of using it (https://github.com/nmattia/naersk/issues/93). After that, you can knock yourself out :)

**Comment by angerman** [comment]
hooray, I've just bumped into this as well. Looking at #98, and specifically at

https://github.com/nmattia/naersk/pull/98/files#diff-6938ea327f87ba609b4fafc30775f3e9R38-R39

I'm left to believe that cross compilation should be as easy as setting a different
`CARGO_BUILD_TARGET`? How does that inherit the toolchain? And what about rust libraries that link against system libraries and would expect those to be cross compiled as well?

**Comment by cpick** [comment]
There's now [an example](https://github.com/nix-community/naersk/tree/master/examples/static-musl) for building against musl.

**Comment by expipiplus1** [comment]
Thank you! If only I could remember what I initially needed this for!
